export const meta = {
  id: "warszawa-2027",
  name: "Półmaraton Warszawski 2027",
  title: "Półmaraton<br><em>Warszawski</em> 2027",
  eyebrow: "Plan treningowy · Daniels, VDOT 40",
  planStart: "2026-10-05",
  raceDate: "2027-04-04",
  quality: {
    Wt: "J2",
    Czw: "J3",
    Nd: "J1",
  },
  stats: [
    {
      label: "Start",
      value: "04.04.2027",
    },
    {
      label: "Cel",
      value: "sub 1:47",
      accent: true,
    },
    {
      label: "Tygodnie",
      value: "8 + 18",
    },
    {
      label: "Baza",
      value: "35–40 km",
    },
  ],
  legend: [
    {
      title: "Założenia",
      html: "<p>Plan prowadzi do półmaratonu w niedzielę 4 kwietnia 2027 r.: 8 tygodni bazy (od 5 października), potem 18 tygodni planu Danielsa (od 30 listopada).</p>",
      facts: [
        {
          label: "Punkt wyjścia",
          text: "VDOT 40 (półmaraton 1:50:00), obecnie 35–40 km tygodniowo.",
        },
        {
          label: "4 dni biegowe",
          text: "wtorek, czwartek, sobota, niedziela. Poniedziałek, środa i piątek to dni wolne lub ćwiczenia ogólnorozwojowe.",
        },
        {
          label: "Sesje J (jakościowe)",
          text: "niedziela = <span class=\"q-tag q-tag-j1\">J1</span> (bieg długi lub M), wtorek = <span class=\"q-tag q-tag-j2\">J2</span> (próg P), czwartek = <span class=\"q-tag q-tag-j3\">J3</span> (rytmy R lub interwały I). Sobota to spokojny bieg z przebieżkami.",
        },
        {
          label: "Kilometraż",
          text: "od ok. 38 km do szczytu ok. 50 km w tygodniach 9–12, z lżejszym tygodniem co 3–4 tygodnie.",
        },
        {
          label: "Cel",
          text: "zejście poniżej 1:47 (VDOT ok. 42). Tempo startowe ustalisz po starcie kontrolnym na 10 km w tygodniu 10.",
        },
      ],
      callout: {
        title: "Jedno odstępstwo od Danielsa",
        text: "przy 4 dniach biegania limit 25% tygodniowego kilometrażu dałby bieg długi 10–12 km, za krótki na półmaraton. Dlatego bieg długi ma do ok. 35% tygodnia, ale zawsze najwyżej 120 minut.",
      },
    },
    {
      title: "Zasady i korekty",
      rules: [
        {
          num: "1",
          label: "Brakuje czasu",
          text: "najpierw rezygnujesz z sobotniego BS, potem z <span class=\"q-tag q-tag-j3\">J3</span>. <span class=\"q-tag q-tag-j1\">J1</span> i <span class=\"q-tag q-tag-j2\">J2</span> robisz zawsze.",
        },
        {
          num: "2",
          label: "Nie przyspieszasz",
          text: "I i R biegasz dokładnie w tempie z tabeli, także w dobry dzień. Trudność zmieniasz długością przerwy.",
        },
        {
          num: "3",
          label: "Choroba lub przerwa",
          text: "do 5 dni wracasz do planu. Po 6–28 dniach powtarzasz ostatni ukończony tydzień i biegasz na tempach o 1–2 punkty VDOT niższych.",
        },
        {
          num: "4",
          label: "Przemęczenie",
          text: "(ciężkie nogi kilka dni z rzędu, tętno spoczynkowe wyższe o 5+ uderzeń): najbliższą sesję J zamieniasz na BS.",
        },
        {
          num: "5",
          label: "Nowy VDOT",
          text: "tempa podnosisz tylko po wyniku z zawodów lub teście, najwcześniej co 4–6 tygodni.",
        },
        {
          num: "6",
          label: "Wiatr, upał, górki",
          text: "trzymasz wysiłek, a nie tempo. Na BS możesz biec wolniej niż 6:45.",
        },
        {
          num: "7",
          label: "Siła",
          text: "w dni wolne 2× w tygodniu 20–30 min ćwiczeń ogólnorozwojowych (przysiady, wykroki, plank, łydki).",
        },
      ],
    },
    {
      title: "Tempa treningowe (VDOT 40)",
      html: "<p>Wszystkie treningi biegasz na tych tempach, dopóki nowy wynik z zawodów nie podniesie VDOT. Wartości są przybliżone, z tabel Danielsa.</p>",
      cards: [
        {
          cls: "card-bs",
          abbr: "BS / BD",
          name: "E",
          desc: "Tempo /km: 6:05–6:45<br>Limit w jednej sesji: BD maks. 120 min",
        },
        {
          cls: "card-m",
          abbr: "M",
          name: "maraton",
          desc: "Tempo /km: ok. 5:26",
        },
        {
          cls: "card-tp",
          abbr: "P",
          name: "próg",
          desc: "Tempo /km: ok. 5:06<br>Na odcinkach: 1000 m ≈ 5:06, 1600 m ≈ 8:10<br>Limit w jednej sesji: ok. 10% tygodnia, maks. 60 min",
        },
        {
          cls: "card-i",
          abbr: "I",
          name: "interwał",
          desc: "Tempo /km: ok. 4:40<br>Na odcinkach: 800 m ≈ 3:44, 1000 m ≈ 4:40, 1200 m ≈ 5:36<br>Limit w jednej sesji: odcinek maks. 5 min; ok. 8% tygodnia",
        },
        {
          cls: "card-r",
          abbr: "R",
          name: "rytm",
          desc: "Tempo /km: ok. 4:25<br>Na odcinkach: 200 m ≈ 53 s, 400 m ≈ 1:46<br>Limit w jednej sesji: ok. 5% tygodnia",
        },
        {
          cls: "card-p",
          abbr: "PB",
          name: "przebieżki",
          desc: "Tempo /km: swobodnie szybko<br>Na odcinkach: 20 s<br>Limit w jednej sesji: przerwa min. 60 s truchtem",
        },
      ],
      after: "<p>Każdy trening jakościowy ma rozpisaną całość: 20 min BS rozgrzewki, część główną z tempem w nawiasie i 10 min BS schłodzenia. Przerwy przy P to stanie lub marsz, przy I i R trucht.</p>",
    },
  ],
  paces: {
    label: "Tempa VDOT 40",
    note: "(półmaraton 1:50:00)",
    chips: [
      {
        cls: "pace-bs",
        text: "BS/BD 6:05–6:45",
      },
      {
        cls: "pace-m",
        text: "M ~5:26",
      },
      {
        cls: "pace-tp",
        text: "P ~5:06",
      },
      {
        cls: "pace-i",
        text: "I ~4:40",
      },
      {
        cls: "pace-r",
        text: "R ~4:25",
      },
    ],
  },
};

export const phases = [
  {
    id: "p1",
    quality: {
    },
    icon: "🧱",
    title: "Baza — biegi spokojne i podbiegi",
    dates: "5.10 – 29.11.2026",
    weeks: [
      {
        id: "B1",
        label: "Baza · ok. 36 km",
        dates: "5–11.10",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "8 km BS (6:05–6:45)",
          Śr: null,
          Czw: "8 km BS (6:05–6:45) + 6 PB",
          Pt: null,
          Sob: "7 km BS (6:05–6:45)",
          Nd: "13 km BD (6:05–6:45)",
        },
      },
      {
        id: "B2",
        label: "Baza · ok. 38 km",
        dates: "12–18.10",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "8 km BS (6:05–6:45)",
          Śr: null,
          Czw: "8 km BS (6:05–6:45) + 6 PB",
          Pt: null,
          Sob: "8 km BS (6:05–6:45)",
          Nd: "14 km BD (6:05–6:45)",
        },
      },
      {
        id: "B3",
        label: "Baza · ok. 40 km",
        dates: "19–25.10",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "9 km BS (6:05–6:45)",
          Śr: null,
          Czw: "8 km BS (6:05–6:45) + 6 PB",
          Pt: null,
          Sob: "8 km BS (6:05–6:45)",
          Nd: "15 km BD (6:05–6:45)",
        },
      },
      {
        id: "B4",
        label: "Baza · lżejszy tydzień · ok. 35 km",
        dates: "26.10–1.11",
        typ: "regen",
        days: {
          Pn: null,
          Wt: "8 km BS (6:05–6:45)",
          Śr: null,
          Czw: "7 km BS (6:05–6:45) + 6 PB",
          Pt: null,
          Sob: "7 km BS (6:05–6:45)",
          Nd: "13 km BD (6:05–6:45)",
        },
      },
      {
        id: "B5",
        label: "Baza · ok. 40 km",
        dates: "2–8.11",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "9 km BS (6:05–6:45)",
          Śr: null,
          Czw: "8 km BS (6:05–6:45) + 6 podbiegów + 5 min truchtu",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "15 km BD (6:05–6:45)",
        },
      },
      {
        id: "B6",
        label: "Baza · ok. 42 km",
        dates: "9–15.11",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "9 km BS (6:05–6:45)",
          Śr: null,
          Czw: "9 km BS (6:05–6:45) + 8 podbiegów + 5 min truchtu",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "16 km BD (6:05–6:45)",
        },
      },
      {
        id: "B7",
        label: "Baza · ok. 44 km",
        dates: "16–22.11",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "10 km BS (6:05–6:45)",
          Śr: null,
          Czw: "9 km BS (6:05–6:45) + 10 podbiegów + 5 min truchtu",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 8 PB",
          Nd: "17 km BD (6:05–6:45)",
        },
      },
      {
        id: "B8",
        label: "Baza · ok. 40 km",
        dates: "23–29.11",
        typ: "bud",
        days: {
          Pn: null,
          Wt: "9 km BS (6:05–6:45)",
          Śr: null,
          Czw: "8 km BS (6:05–6:45) + 8 PB",
          Pt: null,
          Sob: "8 km BS (6:05–6:45)",
          Nd: "15 km BD (6:05–6:45)",
        },
      },
    ],
  },
  {
    id: "p2",
    icon: "⚡",
    title: "Faza II — Rytmy i próg",
    dates: "30.11.2026 – 10.01.2027",
    weeks: [
      {
        id: "T1",
        label: "P 3×1,6 km · R 8×200 m · ok. 40 km",
        dates: "30.11–6.12",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 3×1,6 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 8×200 m R (53 s) + 10 min BS\n(przerwa 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "15 km BD (6:05–6:45)",
        },
      },
      {
        id: "T2",
        label: "P 20 min · R 6×400 m · ok. 41 km",
        dates: "7–13.12",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 20 min P (5:06) + 10 min BS\n(ciągły bieg progowy)",
          Śr: null,
          Czw: "20 min BS + 6×400 m R (1:46) + 10 min BS\n(przerwa 400 m trucht, ok. 3 min)",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "16 km BD (6:05–6:45)",
        },
      },
      {
        id: "T3",
        label: "P 4×1,2 km · R · 8 km M · ok. 38 km",
        dates: "14–20.12",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 4×1,2 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 2× (200 m R (53 s) + 200 m R (53 s) + 400 m R (1:46)) + 10 min BS\n(przerwa po 200 m: 200 m trucht, ok. 1:30; po 400 m: 400 m trucht, ok. 3 min)",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "20 min BS + 8 km M (5:26) + 10 min BS",
        },
      },
      {
        id: "T4",
        label: "Lżejszy tydzień (święta) · ok. 36 km",
        dates: "21–27.12",
        typ: "regen",
        days: {
          Pn: null,
          Wt: "20 min BS + 3×1,6 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 8×200 m R (53 s) + 10 min BS\n(przerwa 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "7 km BS (6:05–6:45)",
          Nd: "12 km BD (6:05–6:45)",
        },
      },
      {
        id: "T5",
        label: "P 5×1 km · R 10×200 m · BD 17 km · ok. 44 km",
        dates: "28.12–3.01",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 5×1 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 10×200 m R (53 s) + 10 min BS\n(przerwa 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "9 km BS (6:05–6:45) + 6 PB",
          Nd: "17 km BD (6:05–6:45)",
        },
      },
      {
        id: "T6",
        label: "P 20 min · R 6×400 m · 10 km M · ok. 40 km",
        dates: "4–10.01",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 20 min P (5:06) + 10 min BS\n(ciągły bieg progowy)",
          Śr: null,
          Czw: "20 min BS + 6×400 m R (1:46) + 10 min BS\n(przerwa 400 m trucht, ok. 3 min)",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "20 min BS + 10 km M (5:26) + 10 min BS",
        },
      },
    ],
  },
  {
    id: "p3",
    icon: "🔥",
    title: "Faza III — Interwały i próg",
    dates: "11.01 – 21.02.2027",
    weeks: [
      {
        id: "T7",
        label: "Pierwsze I 3×1,2 km · ok. 44 km",
        dates: "11–17.01",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 3×1,6 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 3×1,2 km I (4:40) + 10 min BS\n(przerwa 3 min trucht)",
          Pt: null,
          Sob: "8 km BS (6:05–6:45) + 6 PB",
          Nd: "17 km BD (6:05–6:45)",
        },
      },
      {
        id: "T8",
        label: "I 4×1 km · 12 km M · ok. 45 km",
        dates: "18–24.01",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 2×2 km P (5:06) + 10 min BS\n(przerwa 2 min marsz)",
          Śr: null,
          Czw: "20 min BS + 4×1 km I (4:40) + 10 min BS\n(przerwa 3 min trucht)",
          Pt: null,
          Sob: "9 km BS (6:05–6:45) + 6 PB",
          Nd: "20 min BS + 12 km M (5:26) + 10 min BS",
        },
      },
      {
        id: "T9",
        label: "P + R · I 4×1 km · BD 18 km · ok. 48 km",
        dates: "25–31.01",
        typ: "szczyt",
        days: {
          Pn: null,
          Wt: "20 min BS + 3×1,6 km P (5:06) + 4×200 m R (53 s) + 10 min BS\n(przerwa po P: 1 min marsz; po R: 200 m trucht, ok. 1:30)",
          Śr: null,
          Czw: "20 min BS + 4×1 km I (4:40) + 10 min BS\n(przerwa 3 min trucht)",
          Pt: null,
          Sob: "9 km BS (6:05–6:45) + 6 PB",
          Nd: "18 km BD (6:05–6:45)",
        },
      },
      {
        id: "T10",
        label: "Lżejszy · start kontrolny 10 km · ok. 36 km",
        dates: "1–7.02",
        typ: "test",
        days: {
          Pn: null,
          Wt: "20 min BS + 20 min P (5:06) + 10 min BS\n(ciągły bieg progowy)",
          Śr: null,
          Czw: "45 min BS (6:05–6:45) + 6 PB",
          Pt: null,
          Sob: "30 min BS (6:05–6:45) + 4 PB",
          Nd: "15–20 min BS + 4 PB + <strong>start 10 km</strong> (od 5:00, końcówka na maksa)\n+ 10 min truchtu",
        },
        quality: {
          Wt: "J2",
          Nd: "J1",
        },
      },
      {
        id: "T11",
        label: "P 3,2 + 1,6 km · BD 19 km · ok. 48 km",
        dates: "8–14.02",
        typ: "szczyt",
        days: {
          Pn: null,
          Wt: "20 min BS + 3,2 km P (5:06) + 1,6 km P (5:06) + 10 min BS\n(przerwa 2 min marsz)",
          Śr: null,
          Czw: "20 min BS + 3×1,2 km I (4:40) + 4×200 m R (53 s) + 10 min BS\n(przerwa po I: 3 min trucht; po R: 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "9 km BS (6:05–6:45) + 6 PB",
          Nd: "19 km BD (6:05–6:45), maks. 120 min",
        },
      },
      {
        id: "T12",
        label: "I 4×1 km · 12 km M + P · ok. 49 km",
        dates: "15–21.02",
        typ: "szczyt",
        days: {
          Pn: null,
          Wt: "20 min BS + 4×1,2 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 4×1 km I (4:40) + 10 min BS\n(przerwa 3 min trucht)",
          Pt: null,
          Sob: "10 km BS (6:05–6:45) + 6 PB",
          Nd: "20 min BS + 12 km M (5:26) + 1,6 km P (5:06) + 10 min BS\n(bez przerw)",
        },
      },
    ],
  },
  {
    id: "p4",
    icon: "🏁",
    title: "Faza IV — Specyfika półmaratonu i start",
    dates: "22.02 – 4.04.2027",
    weeks: [
      {
        id: "T13",
        label: "P 2×10 min · P + I · ok. 47 km",
        dates: "22–28.02",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 2×10 min P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 3×5 min P (5:06) + 3×3 min I (4:40) + 10 min BS\n(przerwa po P: 1 min marsz; po I: 2 min trucht)",
          Pt: null,
          Sob: "9 km BS (6:05–6:45) + 6 PB",
          Nd: "19 km BD (6:05–6:45)",
        },
      },
      {
        id: "T14",
        label: "I 5×800 m · 2×30 min M · ok. 45 km",
        dates: "1–7.03",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 3×1,6 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 5×800 m I (4:40) + 10 min BS\n(przerwa 400 m trucht, ok. 3 min)",
          Pt: null,
          Sob: "10 km BS (6:05–6:45) + 6 PB",
          Nd: "15 min BS + 30 min M (5:26) + 5 min P (5:06) + 30 min M (5:26) + 10 min BS\n(bez przerw)",
        },
      },
      {
        id: "T15",
        label: "P 20 + 5 min · BD 18 km · ok. 46 km",
        dates: "8–14.03",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 20 min P (5:06) + 5 min P (5:06) + 10 min BS\n(przerwa 3 min marsz)",
          Śr: null,
          Czw: "20 min BS + 3×1 km I (4:40) + 4×200 m R (53 s) + 10 min BS\n(przerwa po I: 3 min trucht; po R: 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "9 km BS (6:05–6:45) + 6 PB",
          Nd: "18 km BD (6:05–6:45)",
        },
      },
      {
        id: "T16",
        label: "Taper · 60 min M · ok. 41 km",
        dates: "15–21.03",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 5×1 km P (5:06) + 10 min BS\n(przerwa 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 8×200 m R (53 s) + 10 min BS\n(przerwa 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "8 km BS (6:05–6:45)",
          Nd: "20 min BS + 60 min M (5:26) + 10 min BS",
        },
      },
      {
        id: "T17",
        label: "Taper · 90 min BS · ok. 38 km",
        dates: "22–28.03",
        typ: "jak",
        days: {
          Pn: null,
          Wt: "20 min BS + 2×10 min P (5:06) + 2×5 min P (5:06) + 10 min BS\n(przerwa po 10 min: 2 min marsz; po 5 min: 1 min marsz)",
          Śr: null,
          Czw: "20 min BS + 6×200 m R (53 s) + 10 min BS\n(przerwa 200 m trucht, ok. 1:30)",
          Pt: null,
          Sob: "7 km BS (6:05–6:45)",
          Nd: "90 min BS (6:05–6:45), ok. 14 km",
        },
      },
      {
        id: "T18",
        label: "Tydzień startowy · ok. 41 z startem km",
        dates: "29.03–4.04",
        typ: "start",
        days: {
          Pn: null,
          Wt: "20 min BS + 3×1,6 km P (5:06) + 10 min BS\n(przerwa 2 min marsz)",
          Śr: null,
          Czw: "30 min BS (6:05–6:45) + 4 PB",
          Pt: null,
          Sob: "20 min BS (6:05–6:45) + 4 PB",
          Nd: "15 min BS + 4 PB + <strong>START 21,1 km (4.04)</strong> w tempie startowym, patrz niżej",
        },
        quality: {
          Wt: "J2",
          Nd: "J1",
        },
      },
    ],
  },
];
